"""2019.01.01-15.05.12

Revision ID: 1737872fc757
Revises: 6d4095cb27af
Create Date: 2019-01-01 15:05:12.906064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1737872fc757'
down_revision = '6d4095cb27af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dummy_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy_model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('string', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('int_zahl', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('float_zahl', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bool', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dummy_model_pkey')
    )
    # ### end Alembic commands ###
