"""2019.01.01-14.33.52

Revision ID: 6d4095cb27af
Revises: e77714f3f490
Create Date: 2019-01-01 14:33:53.075740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4095cb27af'
down_revision = 'e77714f3f490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string', sa.String(length=80), nullable=True),
    sa.Column('int_zahl', sa.Integer(), nullable=True),
    sa.Column('float_zahl', sa.Float(), nullable=True),
    sa.Column('bool', sa.Boolean(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dummy_model')
    # ### end Alembic commands ###
