"""2019.01.03-16.00.06

Revision ID: 83a07b74e276
Revises: 
Create Date: 2019-01-03 16:00:08.116267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a07b74e276'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string', sa.String(length=80), nullable=True),
    sa.Column('int_zahl', sa.Integer(), nullable=True),
    sa.Column('float_zahl', sa.Float(), nullable=True),
    sa.Column('bool', sa.Boolean(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dummy_model')
    # ### end Alembic commands ###
