"""update

Revision ID: 9bd1d1bd6a6d
Revises: c022ace23f34
Create Date: 2018-12-31 17:26:09.826545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd1d1bd6a6d'
down_revision = 'c022ace23f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_model', 'nochmal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_model', sa.Column('nochmal', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
