"""2019.01.01-15.11.56

Revision ID: bc8f5ba78264
Revises: 1737872fc757
Create Date: 2019-01-01 15:11:57.698690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8f5ba78264'
down_revision = '1737872fc757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string', sa.String(length=80), nullable=True),
    sa.Column('int_zahl', sa.Integer(), nullable=True),
    sa.Column('float_zahl', sa.Float(), nullable=True),
    sa.Column('bool', sa.Boolean(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dummy_model')
    # ### end Alembic commands ###
