"""update

Revision ID: c022ace23f34
Revises: bb1c5bc39eed
Create Date: 2018-12-31 17:23:07.252852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c022ace23f34'
down_revision = 'bb1c5bc39eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_model', sa.Column('nochmal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_model', 'nochmal')
    # ### end Alembic commands ###
